services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  # redis:
  #   image: redis:6-alpine
  #   container_name: redis
  #   volumes:
  #     - ./data/config/redis.conf:/usr/local/etc/redis/redis.conf
  #     - ./data/redis:/data
  #   ports:
  #     - 6379:6379
  #   command: redis-server /usr/local/etc/redis/redis.conf
volumes:
  mongo-data:
    driver: local